### ISSUE TITLE
Liveness/readiness probes time out with default deny all network policy on Windows 2022

### ISSUE THREAD

**Issue by maxhov** [Azure/azure-container-networking#1881]
**What happened:**  
There seems to be a difference between Linux and Windows in how liveness/readiness probes are allowed through NPM. We have an application that consists of both Windows and Linux services. Our cluster consists of multiple node pools and generally divided into two categories: Windows 2022 and Linux. 

We apply the following _default_ network policy in the namespace (that contains both Windows and Linux pods) to deny all traffic by default:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default
spec:
  podSelector: { }
  policyTypes:
    - Ingress
    - Egress
```

Probes on Linux nodes work without any issue. However, on Windows the probes time out. When we remove the default network policy, the probes start to work on Windows as well.

I am not sure if the behaviour is wrong on Linux or Windows, but I cannot find any information on how to whitelist liveness/readiness probes in NPM configuration, so I am under the assumption that probes should work without any configuruation in a NetworkPolicy.

**What you expected to happen:**  
Probes work in a consistent manner between OS types. E.g. they should either work or not work on both Windows and Linux when a default deny policy is set. 

**How to reproduce it:**  
Add the following default NetworkPolicy to a namespace that has Windows pods:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default
spec:
  podSelector: { }
  policyTypes:
    - Ingress
    - Egress
```

Add a liveness/readiness probe to the container in the namespace and observe probe time outs.

**Kubernetes Version:**  
v1.25.5

**Kernel (e.g. `uname -a`):**  
Not sure about the kernel version, but we are running the following node images:

Linux: AKSUbuntu-2204gen2containerd-2023.01.26
Windows: AKSWindows-2022-containerd-20348.1547.230223
