### ISSUE TITLE
Update Azure CNI v1 nodeAffinity labels

### ISSUE THREAD

**Issue by nawazkh** [Azure/azure-container-networking#1897]
**What happened:** 
Applying Azure CNI v1 manifest (hosted in the repo at [hack/manifests/cni-installer-v1.yaml](https://github.com/Azure/azure-container-networking/blob/master/hack/manifests/cni-installer-v1.yaml)) does not create the desired `azure-cni` daemonsets(DS). 
I see the below status after applying the DS manifest. 
```
NAMESPACE     NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR              AGE
kube-system   azure-cni                    0         0         0       0            0           <none>                     2m10s
```

**What you expected to happen:**  
- `azure-cni` ds to be created.

**How to reproduce it:**  
- Bring up a CAPZ cluster using the steps mentioned at 
  - https://capz.sigs.k8s.io/topics/getting-started.html
  - https://cluster-api.sigs.k8s.io/user/quick-start.html
- Once the workload cluster is up, expect the MachineDeployment to be in `READY: FALSE` state with the `REASON: WaitingForAvailableMachines`
- Apply the [hack/manifests/cni-installer-v1.yaml](https://github.com/Azure/azure-container-networking/blob/master/hack/manifests/cni-installer-v1.yaml) manifest. 

**Orchestrator and Version (e.g. Kubernetes, Docker):**  
- Kubernetes : `v4.5.7`
- Docker : `20.10.23`

**Operating System (Linux/Windows):**  
- Linux

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**

**Anything else we need to know?:**
[Miscellaneous information that will assist in solving the issue.]
- I got this manifest working by updating the `nodeAffinity` ([ref in the manifest](https://github.com/Azure/azure-container-networking/blob/4e94aca307dfe824fea166a8fa1856eb7c4c1756/hack/manifests/cni-installer-v1.yaml#L20-L33)) to below
```yaml
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
```
