### ISSUE TITLE
10-azure.conflist missing from AKS AzureLinux/CBLMariner node image

### ISSUE THREAD

**Issue by fozturner** [Azure/azure-container-networking#2779]
**What happened:** 
Following updating AKS node images to version `AKSCBLMariner-V2gen2-202405.20.0` we have noticed that there is a CNI conflist file `/etc/cni/net.d/10-azure.conflist` that is now missing from the new nodes. 

This issue is present on the even newer `AKSCBLMariner-V2gen2-202405.27.0` node image too. 

**What you expected to happen:**  
Nodes with CNI enabled should have the `/etc/cni/net.d/10-azure.conflist` file.

**How to reproduce it:**  
Existing cluster - update node image `AKSCBLMariner-V2gen2-202405.20.0` or `AKSCBLMariner-V2gen2-202405.27.0`, run `kubectl debug node/<NODE-NAME> -it --image=mcr.microsoft.com/cbl-mariner/busybox:2.0`, navigate to `/host/etc/cni/net.d/` and the `10-azure.conflist` file isn't in the directory.

**Orchestrator and Version (e.g. Kubernetes, Docker):**  
AKS version 1.27.9

**Operating System (Linux/Windows):**  
Linux

**Kernel:**
`Linux aks-apppool-19864785-vmss00003U 5.15.153.1-2.cm2 #1 SMP Thu Apr 25 16:39:35 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Anything else we need to know?:**

Network-Plugin is set to "Azure" on the AKS clusters.

AKS clusters running older version of the node image still work fine when scaled (ie file is present).

Noticed that the "azure-cns" daemonset only has configuration for the "15-azure-swift.conflist" file and not for the "10-azure.conflist" file.

```
      initContainers:
      - args:
        - deploy
        - --skip-verify
        - azure-vnet
        - -o
        - /opt/cni/bin/azure-vnet
        - azure-vnet-telemetry
        - -o
        - /opt/cni/bin/azure-vnet-telemetry
        - azure-swift.conflist
        - -o
        - /etc/cni/net.d/15-azure-swift.conflist
        command:
        - /dropgz
        image: mcr.microsoft.com/containernetworking/cni-dropgz:v0.0.20
        imagePullPolicy: IfNotPresent
        name: init-cni-dropgz
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/cni/bin
          name: cni-bin
        - mountPath: /etc/cni/net.d
          name: cni-conflist
```

CNI version: 
```
/host/opt/cni/bin # ./azure-vnet --version
Azure CNI Version v1.4.54
```

Related to Azure/AgentBaker/issues/4499
