### ISSUE TITLE
Bad result returned if endpoint attach fails because container has stopped

### ISSUE THREAD

**Issue by PatrickLang** [Azure/azure-container-networking#436]
**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue
**Which release version?**: 1.0.27
**Which component (CNI/IPAM/CNM/CNS)**: CNI
**Which Operating System (Linux/Windows)**: Windows Server 2019
**Which Orchestrator and version (e.g. Kubernetes, Docker)**: Kubernetes

**What happened**:

A container in a pod was stopping before the network endpoint was attached by CNI. In this case, a malformed result is passed back to the kubelet, causing this message in the logs.

```
E1110 14:23:32.842611    4564 cni_windows.go:50] error while adding to cni network: invalid character '{' after top-level value
W1110 14:23:32.842611    4564 docker_sandbox.go:384] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "<name removed>": invalid character '{' after top-level value
```

**What you expected to happen**:

I would expect a well-formed error to be returned that has a message stating "A virtual machine or container with the specified identifier does not exist". Parsing errors make the kubelet logs difficult to understand and don't help identify the root cause of a failure.

**Comment by PatrickLang** [comment]
Here's an easy repro. kubectl create this

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash1
  labels:
    app: crash1
spec:
  replicas: 1
  template:
    metadata:
      name: crash1
      labels:
        app: crash1
    spec:
      containers:
      - name: windowswebserver
        resources:
          limits:
            cpu: .5
            memory: 2Gi
        image: mcr.microsoft.com/windows/servercore:ltsc2019
        command:
        - cmd.exe
        - /c
        - exit 2
      nodeSelector:
        "beta.kubernetes.io/os": windows
  selector:
    matchLabels:
      app: crash1
```
