### ISSUE TITLE
[NPM]Connections to Kubernetes Services with no endpoints hang

### ISSUE THREAD

**Issue by mainred** [Azure/azure-container-networking#569]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE 

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

Kubernetes

---

**What happened**:

Connections to Kubernetes Services with no endpoints hang. Please refer to [calico counterpart issue](https://github.com/projectcalico/calico/issues/1055) for more info

---

create a service

```
apiVersion: v1
kind: Service
metadata:
  name: svc-access-server
spec:
  clusterIP: 10.0.105.125
  ports:
  - name: serve-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: serve-81
    port: 81
    protocol: TCP
    targetPort: 81
  selector:
    app: server

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress


----
apiVersion: v1
kind: Pod
metadata:
  name: client-cni-network
spec:
  containers:
  - command:
    - sleep
    - "1000"
    image: busybox:1.31.1

---
apiVersion: v1
kind: Pod
metadata:
  name: client-hostnetwork
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - command:
    - sleep
    - "1000"
    image: busybox:1.31.1
    imagePullPolicy: IfNotPresent
    name: probe
```

**What you expected to happen**:

```
 kubectl exec -it client-cni-network -- wget svc-access-server --timeout=5
```
The request should be timed out unexpectedly

```
kubectl exec -it  hostnetwork -- wget svc-access-server --timeout=5
```
The request is rejected as expected

---

**How to reproduce it** (as minimally and precisely as possible):

---

**Anything else we need to know**:
When you want to add enpoint to the service, this may help you.
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: server
  name: access-server
spec:
  containers:
  - args:
    - python -m SimpleHTTPServer 80
    command:
    - sh
    - -c
    image: python:2.7.11-alpine
    name: pod-container-80
    ports:
    - containerPort: 80
      name: serve-80
      protocol: TCP
  - args:
    - python -m SimpleHTTPServer 81
    command:
    - sh
    - -c
    image: python:2.7.11-alpine
    name: pod-container-81
    ports:
    - containerPort: 81
      name: serve-81
      protocol: TCP

```
---
