### ISSUE TITLE
[NPM] TO/FROM rule and port rule on same PodSelector in multiple policies is having issues.

### ISSUE THREAD

**Issue by vakalapa** [Azure/azure-container-networking#870]
**What happened:**  

If there are 2((or more) different policies being applied on the same PodSelector and these policies contain TO/FROM rule and PORT rule separately, then TO/FROM rule traffic is being dropped. This does not happen if any of the policies has  both To/FROM rules and PORT rules, then this issue does not occur.

This happens because RETURN rule for a MARKED packet is not added after EGRESS-TO or INGRESS-FROM chains. 

**How to reproduce it:**  

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-to-frontend-on-port-8000-policy
  namespace: testnamespace
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app: frontend
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - port: 8000
---
 apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-all-ns
  namespace: testnamespace
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app: "frontend"
  ingress:
    - from:
        - namespaceSelector: {}
```

Apply the above policy and try to reach Pod with "app: frontend" from other namespaces' Pod, requests/ping will timeout

**How to mitigate **

Combining the Port rules and TO/FROM rules into a single policy will help mitigate the issue. We can combine the above two policies as follow:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-to-frontend-on-port-8000-policy
  namespace: testnamespace
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app: frontend
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - port: 8000
    - from:
        - namespaceSelector: {}
```

This does not change the way policy behaves and mitigates from hitting the issue.
